Repository hmcts/dg-docassembly-api, pull requests merged in 2020-11, with the labels that each got.

#225 Updated cnp-module-key-vault branch
  config/owasp/dependency-check-suppressions.xml
  infrastructure/main.tf
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-225

#227 Updated terraform version
  infrastructure/.terraform-version
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-227

#211 Updated java chart version
  build.gradle
  charts/dg-docassembly/Chart.yaml
  charts/dg-docassembly/requirements.yaml
  charts/dg-docassembly/values.yaml
  config/owasp/dependency-check-suppressions.xml
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/uk/gov/hmcts/reform/dg/docassembly/config/security/SecurityConfiguration.java
  src/main/resources/application.yaml
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-211

#224 EM-3231- EM-DG API: Update functional and smoke test cases to generat…
  build.gradle
  src/aat/java/uk/gov/hmcts/reform/dg/docassembly/functional/BaseTest.java
  src/aat/java/uk/gov/hmcts/reform/dg/docassembly/functional/DocumentConversionScenarios.java
  src/aat/java/uk/gov/hmcts/reform/dg/docassembly/functional/FormDefinitionResourceTests.java
  src/aat/java/uk/gov/hmcts/reform/dg/docassembly/functional/OpenIdConnectSceanarios.java
  src/aat/java/uk/gov/hmcts/reform/dg/docassembly/functional/TemplateRenditionResourceTests.java
  src/aat/java/uk/gov/hmcts/reform/dg/docassembly/smoke/SmokeTest.java
  src/aat/java/uk/gov/hmcts/reform/dg/docassembly/testutil/TestUtil.java
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-224

#228 Updated azurerm version
  infrastructure/state.tf
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-228

#236 Updated em-test-helper version
  build.gradle
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-236
