Repository hmcts/dg-docassembly-api, pull requests merged in 2020-09, with the labels that each got.

#190 EM:3076 - Enable Nightly Build Pipeline
  Jenkinsfile_nightly
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-190

#194 EM-2549: ZAP Security Configuration for DG-DocAssembly.
  Jenkinsfile_nightly
  audit.json
  build.gradle
  security.sh
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-194

#197 Updated em-test-helper version
  build.gradle
  src/aat/java/uk/gov/hmcts/reform/dg/docassembly/smoke/SmokeTest.java
  src/main/java/uk/gov/hmcts/reform/dg/docassembly/rest/WelcomeResource.java
  src/test/java/uk/gov/hmcts/reform/dg/docassembly/rest/WelcomeResourceTest.java
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-197

#203 Updated azurerm details
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/state.tf
  infrastructure/variables.tf
  infrastructure/versions.tf
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-203

#205 Fix the vault copy issue
  infrastructure/main.tf
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-205
