Repository hmcts/dg-docassembly-api, pull requests merged in 2020-12, with the labels that each got.

#241 EM-3280 - dg-docassembly API - Suppress nightly jobs dependency vulne…
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-241

#242 Suppressed vulnerability
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-242

#243 EM-3262 - Doc-assembly: Add retry logic for failing functional test c…
  src/aat/java/uk/gov/hmcts/reform/dg/docassembly/functional/DocumentConversionScenarios.java
  src/aat/java/uk/gov/hmcts/reform/dg/docassembly/functional/FormDefinitionResourceTests.java
  src/aat/java/uk/gov/hmcts/reform/dg/docassembly/functional/OpenIdConnectSceanarios.java
  src/aat/java/uk/gov/hmcts/reform/dg/docassembly/functional/TemplateRenditionResourceTests.java
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-243

#247 Resolved vulnerabilities
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-247

#248 EM-3305 - Dg-doc assembly API - Update local environment setup instru…
  README.md
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-248
