Repository hmcts/dg-docassembly-api, pull requests merged in 2021-07, with the labels that each got.

#395 Added in fortify library
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
  src/test/resources/logback.xml
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-395

#399 Resolved CVE
  build.gradle
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-399

#401 Added in logging to capture consuming service name
  build.gradle
  src/main/java/uk/gov/hmcts/reform/dg/docassembly/Application.java
  src/main/java/uk/gov/hmcts/reform/dg/docassembly/config/ServiceTokenGeneratorConfiguration.java
  src/main/java/uk/gov/hmcts/reform/dg/docassembly/config/security/SecurityUtils.java
  src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/ServiceNameAspect.java
  src/test/java/uk/gov/hmcts/reform/dg/docassembly/rest/FormDefinitionResourceTest.java
  src/test/java/uk/gov/hmcts/reform/dg/docassembly/rest/TemplateRenditionResourceTest.java
  src/test/java/uk/gov/hmcts/reform/dg/docassembly/service/ServiceNameAspectTest.java
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-401

#406 Resolved slow build issue
  build.gradle
  src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/ServiceNameAspect.java
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-406

#412 Resolved CVE
  build.gradle
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-412

#408 EM-3989-DocAssembly SecurityScan-Fix for nightly pipeline job
  audit.json
  security.sh
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-408

#413 Updated Chart Java version
  charts/dg-docassembly/Chart.yaml
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-413
