Repository hmcts/dg-docassembly-api, pull requests merged in 2021-10, with the labels that each got.

#463 EM-4063: fix dependency check issue
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-463

#464 EM-4063: fix dependency check issue
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-464

#465 Em 4065 resolve error status with code 500
  src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/ServiceNameAspect.java
  src/test/java/uk/gov/hmcts/reform/dg/docassembly/service/ServiceNameAspectTest.java
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-465
