Repository hmcts/dg-docassembly-api, pull requests merged in 2021-06, with the labels that each got.

#368 Fixed Mass Assignment: Insecure Binder Configuration issue
  src/main/java/uk/gov/hmcts/reform/dg/docassembly/config/Constants.java
  src/main/java/uk/gov/hmcts/reform/dg/docassembly/rest/TemplateRenditionResource.java
  src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/TemplateRenditionService.java
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-368

#373 Updated em-test-helper version
  build.gradle
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-373

#375 Fixed CVE
  build.gradle
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-375

#385 whitelist xui to allow conversion of MS Office file types
  src/main/resources/application.yaml
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-385
