Repository hmcts/dg-docassembly-api, pull requests merged in 2021-02, with the labels that each got.

#272 Resolved vulnerability
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-272

#281 Resolved CVE-2021-21290
  build.gradle
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-281

#285 Update DOCMOSIS URL
  charts/dg-docassembly/Chart.yaml
  charts/dg-docassembly/values.yaml
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-285

#286 update TF & gradle
  gradle/wrapper/gradle-wrapper.properties
  infrastructure/.terraform-version
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-286
