Repository hmcts/dg-docassembly-api, pull requests merged in 2021-12, with the labels that each got.

#510 CDAM changes for Document Conversion endpoint
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
  bin/idam-client-setup-roles.sh
  bin/start-local-environment.sh
  build.gradle
  charts/dg-docassembly/Chart.yaml
  charts/dg-docassembly/values.yaml
  database/Dockerfile
  database/create-multiple-postgresql-databases.sh
  docker-compose-dependencies.yml
  src/aat/java/uk/gov/hmcts/reform/dg/docassembly/functional/BaseTest.java
  src/aat/java/uk/gov/hmcts/reform/dg/docassembly/functional/SecureDocumentConversionScenarios.java
  src/aat/java/uk/gov/hmcts/reform/dg/docassembly/functional/TestConfig.java
  src/aat/java/uk/gov/hmcts/reform/dg/docassembly/testutil/ExtendedCcdHelper.java
  src/aat/java/uk/gov/hmcts/reform/dg/docassembly/testutil/TestUtil.java
  src/aat/java/uk/gov/hmcts/reform/dg/docassembly/testutil/ToggleProperties.java
  src/aat/resources/adv_docassembly_functional_tests_ccd_def.xlsx
  src/aat/resources/application.yml
  src/main/java/uk/gov/hmcts/reform/dg/docassembly/dto/ByteArrayMultipartFile.java
  src/main/java/uk/gov/hmcts/reform/dg/docassembly/dto/JwtDto.java
  src/main/java/uk/gov/hmcts/reform/dg/docassembly/dto/TemplateIdDto.java
  src/main/java/uk/gov/hmcts/reform/dg/docassembly/rest/DocumentConversionResource.java
  src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/CdamService.java
  src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/EmCaseDocumentClientApi.java
  src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/FileToPDFConverterService.java
  src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/impl/FileToPDFConverterServiceImpl.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/dg/docassembly/rest/DocumentConversionResourceTest.java
  src/test/java/uk/gov/hmcts/reform/dg/docassembly/service/CdamServiceTest.java
  src/test/java/uk/gov/hmcts/reform/dg/docassembly/service/FileToPDFConverterServiceImplTest.java
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-510

#515 Fixed log4J vulnerability
  build.gradle
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-515

#516 Updated log4J version
  build.gradle
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-516

#517 Update fortifyscan
  Jenkinsfile_nightly
  config/fortify-client.properties
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-517
