Repository hmcts/dg-docassembly-api, pull requests merged in 2021-03, with the labels that each got.

#288 Resolved CVE-2021-22112
  build.gradle
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-288

#289 Updated Sonarqube config
  build.gradle
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-289

#296 Em 3598 update to rse idam simulator
  README.md
  build.gradle
  docker-compose-dependencies-simulator.yml
  src/aat/resources/application.yml
  src/main/resources/application.yaml
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-296

#300 EM-3619 -EM-dg-docassembly-api: suppress security scan errors
  audit.json
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-300

#301 Fixed pact report generation
  build.gradle
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-301

#309 Fixed CVE-2020-15824, CVE-2020-29582
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-309

#307 EM-3638 - EM-dg-docassembly-api: Add functional tests for TemplateRen…
  src/aat/java/uk/gov/hmcts/reform/dg/docassembly/functional/DocumentConversionScenarios.java
  src/aat/java/uk/gov/hmcts/reform/dg/docassembly/functional/FormDefinitionResourceTests.java
  src/aat/java/uk/gov/hmcts/reform/dg/docassembly/functional/TemplateRenditionResourceTests.java
  src/aat/java/uk/gov/hmcts/reform/dg/docassembly/testutil/TestUtil.java
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-307
