Repository hmcts/dg-docassembly-api, pull requests merged in 2021-08, with the labels that each got.

#422 Resolved CVE
  build.gradle
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-422

#423 Suppressed medium vulnerability
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-423

#431 Fix terraform version
  infrastructure/state.tf
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-431
