Repository hmcts/dg-docassembly-api, pull requests merged in 2022-03, with the labels that each got.

#568 update postgres version to 11 for local setup
  database/Dockerfile
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-568

#569 docassembly java chart upgd. Update Chart.yaml
  charts/dg-docassembly/Chart.yaml
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-569

#570 bump java chart
  charts/dg-docassembly/Chart.yaml
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-570

#575 Resolved CVE
  build.gradle
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-575

#576 Upgraded SpringBoot version to 2.6.4
  bin/start-local-environment.sh
  build.gradle
  config/owasp/dependency-check-suppressions.xml
  docker-compose-dependencies.yml
  idam-client-setup.sh
  src/aat/resources/application.yml
  src/main/java/uk/gov/hmcts/reform/dg/docassembly/Application.java
  src/main/java/uk/gov/hmcts/reform/dg/docassembly/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/dg/docassembly/config/security/SecurityConfiguration.java
  src/main/java/uk/gov/hmcts/reform/dg/docassembly/rest/DocumentConversionResource.java
  src/main/java/uk/gov/hmcts/reform/dg/docassembly/rest/FormDefinitionResource.java
  src/main/java/uk/gov/hmcts/reform/dg/docassembly/rest/TemplateRenditionResource.java
  src/main/resources/application.yaml
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-576

#579 Fix security scan
  audit.json
  security.sh
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-579

#580 Nightly build Security Scan fix
  audit.json
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-580

#581 Whitelisted adoption_web
  charts/dg-docassembly/Chart.yaml
  charts/dg-docassembly/values.yaml
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-581

#585 fixed CVE-2022-26336 + CVE-2020-21913
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-585

#586 Update dependabot.yml
  .github/dependabot.yml
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-586

#588 Fix CVE-2020-36518
  build.gradle
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-588

#591 Remove jackson-bom
  build.gradle
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-591

#592 Updated azurerm and terraform version
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/state.tf
  infrastructure/versions.tf
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-592
