Repository hmcts/dg-docassembly-api, pull requests merged in 2022-08, with the labels that each got.

#717 Resolved fortify issue
  docker-compose-demo.yml
  docker-compose-dependencies-simulator.yml
  docker-compose-dependencies.yml
  docker-compose.yml
  docker-pactbroker-compose.yml
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-717

#719 Resolve service exception
  src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/ServiceNameAspect.java
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-719

#730 Add backstage configuration file
  catalog-info.yaml
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-730
