Repository hmcts/dg-docassembly-api, pull requests merged in 2022-09, with the labels that each got.

#740 Resolved CVE
  build.gradle
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-740

#745 Added in dependabot config
  .github/dependabot.yml
  .github/stale.yml
  renovate.json
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-745

#759 Use em-test-helper version 1.21.4
  build.gradle
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-759

#761 Upgrade poi-ooxml
  build.gradle
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-761

#769 Revert "Upgrade poi-ooxml (#761)"
  build.gradle
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-769

#770 EM-4606 copy app-insights-connection-string from rpa
  charts/dg-docassembly/values.yaml
  infrastructure/main.tf
Labels: ns:dg, prd:dg, add-or-update, rel:dg-docassembly-pr-770
