Repository hmcts/dg-docassembly-api, pull requests merged in 2023-09, with the labels that each got.

#1204 Resolve CVE-2023-41080
  build.gradle
Labels: prd:dg, ns:dg, rel:dg-docassembly-pr-1204

#1240 Em 5551 update renovate config
  .github/renovate.json
Labels: prd:dg, add-or-update, ns:dg, rel:dg-docassembly-pr-1240

#1242 Em 5551 update renovate config
  .github/renovate.json
Labels: prd:dg, add-or-update, ns:dg, rel:dg-docassembly-pr-1242

#1249 EM-5551 fix renovate config
  .github/renovate.json
  config/owasp/dependency-check-suppressions.xml
Labels: prd:dg, ns:dg, rel:dg-docassembly-pr-1249
