Repository hmcts/dg-docassembly-api, pull requests merged in 2023-03, with the labels that each got.

#982 Fixed CVE
  build.gradle
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-982

#985 Updated CVE list
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-985

#1018 Updated Dependency
  Dockerfile
  build.gradle
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-1018
