Repository hmcts/dg-docassembly-api, pull requests merged in 2023-04, with the labels that each got.

#1026 Updated CVE list
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-1026

#1033 EM-5186 remove security.sh
  security.sh
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-1033

#1036 Em-5186 suppress sec scan vulnerability
  audit.json
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-1036

#1037 Em-5186 suppress sec scan vulnerability-2
  audit.json
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-1037

#1045 EM-5198 security scan
  audit.json
  functional-output/zap.reports
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-1045

#1048 Em 5193 endpoint to return json
  src/aat/java/uk/gov/hmcts/reform/dg/docassembly/smoke/SmokeTest.java
  src/main/java/uk/gov/hmcts/reform/dg/docassembly/rest/WelcomeResource.java
  src/test/java/uk/gov/hmcts/reform/dg/docassembly/rest/WelcomeResourceTest.java
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-1048

#1044 Em 5184 deploy preview with dependencies
  charts/dg-docassembly/Chart.yaml
  charts/dg-docassembly/values.preview.template.yaml
  charts/dg-docassembly/values.yaml
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-1044

#1053 Added in more logs
  src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/DocmosisApiClient.java
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-1053

#1056 Resolved CVE
  build.gradle
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-1056
