Repository hmcts/dg-docassembly-api, pull requests merged in 2023-07, with the labels that each got.

#1161 upgrade spring boot to 3.1.2
  build.gradle
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-1161

#1164 Resolved CVE & removed redundant CVE
  build.gradle
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-1164

#1170 Updated CVE list
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-1170
