Repository hmcts/dg-docassembly-api, pull requests merged in 2023-01, with the labels that each got.

#901 Suppress CVE
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-901

#903 EM-4943 suppress vulnerability
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-903

#906 Resolved CVE
  build.gradle
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-906

#921 Em 4990 add log
  src/main/java/uk/gov/hmcts/reform/dg/docassembly/rest/TemplateRenditionResource.java
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-921

#922 add log
  src/main/java/uk/gov/hmcts/reform/dg/docassembly/rest/TemplateRenditionResource.java
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-922

#934 EM-5015 bump-hmcts.java
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-934

#937 EM-5019 fix-pipeline
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-937
