Repository hmcts/dg-docassembly-api, pull requests merged in 2023-06, with the labels that each got.

#1097 Em 5300 override appinsight access
  charts/dg-docassembly/values.preview.template.yaml
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-1097

#1112 Resolved CVE
  build.gradle
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-1112

#1105 Em-5123 spring upgrade
  build.gradle
  config/owasp/dependency-check-suppressions.xml
  src/aat/java/uk/gov/hmcts/reform/dg/docassembly/functional/BaseTest.java
  src/aat/java/uk/gov/hmcts/reform/dg/docassembly/functional/OpenIdConnectSceanarios.java
  src/aat/java/uk/gov/hmcts/reform/dg/docassembly/functional/SecureTemplateRenditionResourceTests.java
  src/aat/java/uk/gov/hmcts/reform/dg/docassembly/smoke/SmokeTest.java
  src/aat/java/uk/gov/hmcts/reform/dg/docassembly/testutil/TestUtil.java
  src/main/java/uk/gov/hmcts/reform/dg/docassembly/Application.java
  src/main/java/uk/gov/hmcts/reform/dg/docassembly/config/AppInsight.java
  src/main/java/uk/gov/hmcts/reform/dg/docassembly/config/security/SecurityConfiguration.java
  src/main/java/uk/gov/hmcts/reform/dg/docassembly/dto/CreateTemplateRenditionDto.java
  src/main/java/uk/gov/hmcts/reform/dg/docassembly/dto/TemplateIdDto.java
  src/main/java/uk/gov/hmcts/reform/dg/docassembly/rest/DocumentConversionResource.java
  src/main/java/uk/gov/hmcts/reform/dg/docassembly/rest/TemplateRenditionResource.java
  src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/CdamService.java
  src/test/java/uk/gov/hmcts/reform/dg/docassembly/rest/DocumentConversionResourceTest.java
  src/test/java/uk/gov/hmcts/reform/dg/docassembly/rest/TestSecurityConfiguration.java
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-1105

#1125 upgrade to gradle 8
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-1125

#1131 Updated CVE list
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dg, prd:dg, rel:dg-docassembly-pr-1131
